name: CI Management

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 7
          redis-port: 6379

      - name: Test
        run: npm run coverage

      - name: Check conventional commits
        if: github.event_name == 'pull_request'
        run: |
          # Check if commits follow conventional format
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          # Get commit messages
          COMMITS=$(git log --pretty=format:"%s" $BASE_SHA..$HEAD_SHA)

          # Check each commit
          echo "Checking commit messages for conventional format..."
          echo "$COMMITS" | while IFS= read -r commit; do
            if [[ ! "$commit" =~ ^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?(!)?:\ .+ ]]; then
              echo "❌ Commit message doesn't follow conventional format: $commit"
              echo "Expected format: <type>[optional scope]: <description>"
              exit 1
            else
              echo "✅ $commit"
            fi
          done 